scan_timeout = 10
add_newline = true

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"

[aws.region_aliases]
ap-northeast-1 = "jp"

[custom.arch]
command = "uname -m"
style = "bold yellow"
format = "[$output]($style)"

[docker_context]
format = "via [🐋 $context](blue bold)"

[git_branch]
symbol = " "

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user🌱]($style) "
disabled = false
show_always = true
